### ISSUE TITLE
consistent top and bottom padding for all sections

### ISSUE THREAD

**Issue by ftripier** [fluxio/site-extractor-landing-page#13]

**Comment by viviandien** [comment]
this should be done for web too -->

<img width="774" alt="screen shot 2017-03-15 at 4 51 52 pm" src="https://cloud.githubusercontent.com/assets/6173393/23975805/8c7225ee-09a0-11e7-86d1-8be25d866107.png">
<img width="980" alt="screen shot 2017-03-15 at 4 51 42 pm" src="https://cloud.githubusercontent.com/assets/6173393/23975810/8e66ecf4-09a0-11e7-8ab9-107f569a9068.png">
