### ISSUE TITLE
typo: change 04 caption to "Open with your favorite design tool"

### ISSUE THREAD

**Issue by viviandien** [fluxio/site-extractor-landing-page#25]

**Comment by viviandien** [comment]
<img width="1043" alt="screen shot 2017-03-17 at 2 24 04 pm" src="https://cloud.githubusercontent.com/assets/6173393/24063647/df9bffaa-0b1d-11e7-90d5-bc7bc7a0095e.png">

**Comment by viviandien** [comment]
jk this doesn't matter if we delete the entire section

**Comment by jgumiega** [comment]
Closing - it's not relevant since we removed 4 steps tutorial
